destination: public
source: src
title: Jekyll + Contentful starter repo
sass:
    sass_dir: assets/_sass
    style: compressed
title: Your awesome title
email: your-email@example.com
description: A basic starter repo for a Jekyll build that uses Contentful as a CMS.
contentful:
  spaces:
    - posts:
        base_path: src/
        space: ENV_CONTENTFUL_SPACE
        access_token: ENV_CONTENTFUL_TOKEN
        destination: /
page_gen:
    - data: 'posts.testBlogPost'
      template: 'post'
      name: 'slug'
      base_path: src/
      dir: 'posts'
      index_files: true
